apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniatures-contest-backend.fullname" . }}-secret
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  PG_PASSWORD: {{ .Values.secrets.PG_PASSWORD | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.MINIO_ACCESS_KEY | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.MINIO_SECRET_KEY | quote }}
